lemak_resto/lemak_resto/Models/ErrorViewModel.cs
namespace lemak_resto.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lemak_resto/lemak_resto/Controllers/HomeController.cs
using lemak_resto.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace lemak_resto.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lemak_resto/lemak_resto/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using viewmodel_lemak_resto;

namespace lemak_resto.Controllers
{
    public class MenuController : Controller
    {
        private readonly IWebHostEnvironment? _webHostEnvironment;
        public MenuController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public string Upload(IFormFile imageFile)
        {
            string uniqueFileName = "";

            if (imageFile != null)
            {
                string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    imageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ResponseViewModel Create(MenuViewModel dataParam)
        {
            ResponseViewModel response = new ResponseViewModel();
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }

            response.Success = true;
            response.Message = "Success";
            response.Data = new
            {
                dataParam.ImagePath
            };

            return response;
        }

        public IActionResult Detail()
        {
            return View();
        }

        public IActionResult Update(MenuViewModel dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            return View();
        }
    }
}

lemak_resto/lemak_resto/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;

namespace lemak_resto.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Update()
        {
            return View();
        }

        public IActionResult Detail()
        {
            return View();
        }
    }
}

lemak_resto/lemak_resto/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

lemak_resto/lemak_resto/Views/Menu/Create.cshtml
<form>
    <div class="mb-3">
        <label for="Name" class="form-label">Nama</label>
        <input type="text" class="form-control" id="Name" name="Name">
    </div>

    <div class="mb-3">
        <label for="Description" class="form-label">Deskripsi</label>
        <input type="text" class="form-control" id="Description" name="Description">
    </div>

    <div class="mb-3">
        <label for="Price" class="form-label">Harga</label>
        <input type="number" class="form-control" id="Price" name="Price">
    </div>

    <div class="mb-3">
        <label for="Image" class="form-label">Gambar</label>
        <input class="form-control" type="file" id="Image" name="ImagePath">
    </div>

    <button type="submit" id="btn-submit" class="btn btn-success">Simpan</button>
    <a class="btn btn-primary" asp-controller="Menu" asp-action="Index">Kembali</a>
</form>

<script>
    $("#btn-submit").click(function (e) {
        e.preventDefault();

        var name = $("#Name").val()
        var desc = $("#Description").val()
        var price = $("#Price").val()
        var file = $("#Image").prop("files")[0]
        var data = new FormData()
        data.append("Id", Math.random().toString().substring(3, 103))
        data.append("IsDelete", false)
        data.append("Name", name)
        data.append("Description", desc)
        data.append("ImageFile", file)
        data.append("Price", price)

        $.ajax({
            url: "/Menu/Create",
            method: "post",
            data: data,
            contentType: false,
            processData: false,
            success: function (response) {
                data.append("ImagePath", response.data.imagePath)
                submit(data)
            }
        })
    })

    function submit(data){
        $.ajax({
            url: "https://localhost:7285/api/Menu",
            method: "post",
            data: data,
            contentType: false,
            processData: false,
            // contentType: 'multipart/form-data; charset=utf-8',
            // dataType: "json",
            success: function (response) {
                Swal.fire({
                    text: response.message,
                    icon: "success"
                })

                setTimeout(function () {
                    window.location = "/Menu"
                }, 1000)
            }
        })
    }
</script>

lemak_resto/lemak_resto/Views/Menu/Detail.cshtml
<div class="mb-3">
    <label for="Name" class="form-label">Nama</label>
    <input type="text" class="form-control" id="Name" name="Name" readonly>
</div>

<div class="mb-3">
    <label for="Description" class="form-label">Deskripsi</label>
    <input type="text" class="form-control" id="Description" name="Description" readonly>
</div>

<div class="mb-3">
    <label for="Price" class="form-label">Harga</label>
    <input type="number" class="form-control" id="Price" name="Price" readonly>
</div>

<div class="mb-3">
    <label for="Image" class="form-label">Gambar</label>
    <img src="" alt="gambar" />
</div>

<script>
    $(document).ready(function () {
        var data = new URLSearchParams(window.location.search)

        $.ajax({
            method: 'get',
            url: 'https://localhost:7285/api/Menu/' + data.get("id"),
            success: function (response) {
                $("#Name").val(response.data.name)
                $("#Description").val(response.data.description)
                $("#Price").val(response.data.price)
                // $("#Name").val(response.data.name)
            }

        })
    })
</script>

lemak_resto/lemak_resto/Views/Menu/Index.cshtml
<h1>Menu</h1>

<a class="btn btn-success mb-3" asp-controller="Menu" asp-action="Create">+ Makanan</a>

<div class="row" id="cards">
    
</div>

<script>
    $(document).ready(function () {
        $.ajax({
            url: 'https://localhost:7285/api/Menu',
            method: 'get',
            success: function (result, status) {
                $("#table").empty()
                console.log(result)
                for (var i = 0; i < result.data.length; i++) {

                    $("#cards").append(
                        `<div class="col-4 mb-2">
                            <div class="card" style="width: 18rem;">
                                    <img src="/images/${result.data[i].imagePath}" class="card-img-top" alt="...">
                                <div class="card-body text-center">
                                    <h5 class="card-title">${result.data[i].name}</h5>
                                    <p class="card-text m-0 p-0">${result.data[i].description}</p>
                                    <p class="card-text mb-1 pb-1">${result.data[i].price}</p>
                                    <div>
                                        <a href="/Menu/Update?id=${result.data[i].id}" class="btn btn-primary mb-1">Edit</a>
                                        <a href="/Menu/Detail?id=${result.data[i].id}" class="btn btn-warning mb-1">Detail</a>
                                    </div>
                                    <div>
                                        <a href="#" id="btn-soft-delete" class="btn btn-info mb-1" data-id="${result.data[i].id}">Soft Delete</a>
                                        <a href="#" id="btn-delete" class="btn btn-danger mb-1" data-id="${result.data[i].id}">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>`)
                }
            }
        })

        $(document).on('click', '#btn-delete', function () {
            var id = $(this).attr("data-id")

            $.ajax({
                url: "https://localhost:7285/api/Menu/" + id,
                method: 'delete',
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location.reload()
                    }, 2000)
                }
            })
        })

        $(document).on('click', '#btn-soft-delete', function () {
            var id = $(this).attr("data-id")

            $.ajax({
                url: "https://localhost:7285/api/Menu/" + id,
                method: 'put',
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location.reload()
                    }, 2000)
                }
            })
        })
    })
</script>

lemak_resto/lemak_resto/Views/Menu/Update.cshtml
<form>
    <input type="hidden" class="form-control" id="id" name="Id">

    <div class="mb-3">
        <label for="Name" class="form-label">Nama</label>
        <input type="text" class="form-control" id="Name" name="Name">
    </div>

    <div class="mb-3">
        <label for="Description" class="form-label">Deskripsi</label>
        <input type="text" class="form-control" id="Description" name="Description">
    </div>

    <div class="mb-3">
        <label for="Price" class="form-label">Harga</label>
        <input type="number" class="form-control" id="Price" name="Price">
    </div>

    <div class="mb-3">
        <label for="Image" class="form-label">Gambar</label>
        <img src="" alt="gambar" />
    </div>

    <button type="submit" id="btn-submit" class="btn btn-success">Simpan</button>
    <a class="btn btn-primary" asp-controller="Menu" asp-action="Index">Kembali</a>
</form>


<script>
    $(document).ready(function () {
        var dataId = new URLSearchParams(window.location.search)

        $.ajax({
            method: 'get',
            url: 'https://localhost:7285/api/Menu/' + dataId.get("id"),
            success: function (response) {
                $("#Name").val(response.data.name)
                $("#Description").val(response.data.description)
                $("#Price").val(response.data.price)
                // $("#ImagePath").val(response.data.name)
            }

        })

        $("#btn-submit").click(function (e) {
            e.preventDefault()

            var name = $("#Name").val()
            var desc = $("#Description").val()
            var price = $("#Price").val()
            var file = $("#Image").prop("files")[0]
            var data = new FormData()
            data.append("Id", dataId.get("id"))
            data.append("IsDelete", false)
            data.append("Name", name)
            data.append("Description", desc)
            data.append("ImagePath", file)
            data.append("Price", price)

            $.ajax({
                url: "https://localhost:7285/api/Menu",
                method: "put",
                data: data,
                contentType: false,
                processData: false,
                // contentType: "application/json",
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location = '/Menu'
                    }, 2000)
                }
            })
        })
    })
</script>

lemak_resto/lemak_resto/Views/Role/Create.cshtml
<form>
    <div class="mb-3">
        <label for="Name" class="form-label">Nama Role</label>
        <input type="text" class="form-control" id="Name" name="Name">
    </div>

    <button type="submit" id="btn-submit" class="btn btn-success">Simpan</button>
    <a class="btn btn-primary" asp-controller="Role" asp-action="Index">Kembali</a>
</form>

<script>
    $("#btn-submit").click(function (e) {
        e.preventDefault();

        var name = $("#Name").val()
        var data = {
            Name: name
        }

        $.ajax({
            url: "https://localhost:7285/api/Role",
            method: "post",
            data: JSON.stringify(data),
            contentType: 'application/json; charset=utf-8',
            dataType: "json",
            success: function (response) {
                // console.log(response)
                Swal.fire({
                    text: response.message,
                    icon: "success"
                })

                setTimeout(function () {
                    window.location = "/Role"
                }, 1000)
            }
        })
    })
</script>

lemak_resto/lemak_resto/Views/Role/Detail.cshtml
<form>
    <div class="mb-3">
        <label for="Name" class="form-label">Nama Role</label>
        <input type="text" class="form-control" id="Name" name="Name" readonly>
    </div>

    <a class="btn btn-primary" asp-controller="Role" asp-action="Index">Kembali</a>
</form>

<script>
    $(document).ready(function () {
            var data = new URLSearchParams(window.location.search)
            // alert(data.get("id"))

            $.ajax({
                url: "https://localhost:7285/api/Role/" + data.get("id"),
                method: 'get',
                success: function (response) {
                    $("#Name").val(response.data.name)
                }
            })
    })
</script>

lemak_resto/lemak_resto/Views/Role/Index.cshtml
<h1>Role</h1>

<a class="btn btn-success" asp-controller="Role" asp-action="Create">+ Role</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Nama Role</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody id="table">
        <tr>
        </tr>
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $.ajax({
            url: 'https://localhost:7285/api/Role',
            method: 'get',
            success: function (result, status) {
                $("#table").empty()

                for (var i = 0; i < result.data.length; i++) {

                    $("#table").append(
                        `<tr>
                            <th scope="row"> ${i + 1} </th>
                            <td>${result.data[i].name}</td>
                            <td>
                                <a href="/Role/Update?id=${result.data[i].id}" class='btn btn-primary' data-id="${result.data[i].id}">Edit</a>
                                <a href="/Role/Detail?id=${result.data[i].id}" class='btn btn-warning'>Detail</a>
                                <a class='btn btn-info' id='btn-soft-delete' data-id="${result.data[i].id}">Soft Delete</a>
                                <a class='btn btn-danger' id='btn-delete' data-id="${result.data[i].id}">Delete</a>
                            </td>
                        </tr>`)
                }
            }
        })

        $(document).on('click', '#btn-delete', function () {
            var id = $(this).attr("data-id")

            $.ajax({
                url: "https://localhost:7285/api/Role/" + id,
                method: 'delete',
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location.reload()
                    }, 2000)
                }
            })
        })

        $(document).on('click', '#btn-soft-delete', function () {
            var id = $(this).attr("data-id")

            $.ajax({
                url: "https://localhost:7285/api/Role/" + id,
                method: 'put',
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location.reload()
                    }, 2000)
                }
            })
        })
    })
</script>

lemak_resto/lemak_resto/Views/Role/Update.cshtml
<form>
    <input type="hidden" class="form-control" id="id" name="Id">

    <div class="mb-3">
        <label for="Name" class="form-label">Nama Role</label>
        <input type="text" class="form-control" id="Name" name="Name">
    </div>

    <button type="submit" id="btn-submit" class="btn btn-success">Simpan</button>
    <a class="btn btn-primary" asp-controller="Role" asp-action="Index">Kembali</a>
</form>

<script>
    $(document).ready(function () {
        var data = new URLSearchParams(window.location.search)
        // alert(data.get("id"))

        $.ajax({
            url: "https://localhost:7285/api/Role/" + data.get("id"),
            method: 'get',
            success: function (response) {
                $("#Name").val(response.data.name)
            }
        })

        $("#btn-submit").click(function (e) {
            e.preventDefault()

            var name = $("#Name").val()

            $.ajax({
                url: "https://localhost:7285/api/Role",
                method: "put",
                data: JSON.stringify({ 
                    Id: data.get("id"),
                    Name: name 
                }),
                contentType: "application/json",
                success: function (response) {
                    Swal.fire({
                        text: response.message,
                        icon: "success"
                    })

                    setTimeout(function () {
                        window.location = '/Role'
                    }, 2000)
                }
            })
        })
    })
</script>

lemak_resto/lemak_resto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - lemak_resto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lemak_resto.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/plugins/swal/sweetalert2.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">lemak_resto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Lemak Resto • 2024 • Made with ❤️️
        </div>
    </footer>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>